### ISSUE TITLE
favicon 추가해주세요

### ISSUE THREAD

**Issue by LeeSeungjae00** [HoonMingky/guess-mbti#2]

**Comment by mingkyme** [comment]
<img width="514" alt="image" src="https://github.com/HoonMingky/guess-mbti/assets/45954551/fe8c0b57-b1ae-4a8f-86d7-8ad9f714993d">

초안? 어때요?

**Comment by Hoon-Dev** [comment]
[**PR - [기능] favicon #10**](https://github.com/HoonMingky/guess-mbti-web/pull/10)에 **반영**되었습니다,
**소중한 피드백**에 진심으로 감사드립니다. 🌈
